using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMkvPropEdit.Classes
{
    static class StaticData
    {
        internal static Dictionary<string, string> Languages = new Dictionary<string, string> //Key is Code, value is language name
        {
            {"abk","Abkhazian"},
            {"ace","Achinese"},
            {"ach","Acoli"},
            {"ada","Adangme"},
            {"ady","Adyghe; Adygei"},
            {"aar","Afar"},
            {"afh","Afrihili"},
            {"afr","Afrikaans"},
            {"afa","Afro-Asiatic languages"},
            {"ain","Ainu"},
            {"aka","Akan"},
            {"akk","Akkadian"},
            {"alb","Albanian"},
            {"ale","Aleut"},
            {"alg","Algonquian languages"},
            {"tut","Altaic languages"},
            {"amh","Amharic"},
            {"anp","Angika"},
            {"apa","Apache languages"},
            {"ara","Arabic"},
            {"arg","Aragonese"},
            {"arp","Arapaho"},
            {"arw","Arawak"},
            {"arm","Armenian"},
            {"rup","Aromanian; Arumanian; Macedo-Romanian"},
            {"art","Artificial languages"},
            {"asm","Assamese"},
            {"ast","Asturian; Bable; Leonese; Asturleonese"},
            {"ath","Athapascan languages"},
            {"aus","Australian languages"},
            {"map","Austronesian languages"},
            {"ava","Avaric"},
            {"ave","Avestan"},
            {"awa","Awadhi"},
            {"aym","Aymara"},
            {"aze","Azerbaijani"},
            {"ban","Balinese"},
            {"bat","Baltic languages"},
            {"bal","Baluchi"},
            {"bam","Bambara"},
            {"bai","Bamileke languages"},
            {"bad","Banda languages"},
            {"bnt","Bantu languages"},
            {"bas","Basa"},
            {"bak","Bashkir"},
            {"baq","Basque"},
            {"btk","Batak languages"},
            {"bej","Beja; Bedawiyet"},
            {"bel","Belarusian"},
            {"bem","Bemba"},
            {"ben","Bengali"},
            {"ber","Berber languages"},
            {"bho","Bhojpuri"},
            {"bih","Bihari languages"},
            {"bik","Bikol"},
            {"bin","Bini; Edo"},
            {"bis","Bislama"},
            {"byn","Blin; Bilin"},
            {"zbl","Blissymbols; Blissymbolics; Bliss"},
            {"nob","Bokmål, Norwegian; Norwegian Bokmål"},
            {"bos","Bosnian"},
            {"bra","Braj"},
            {"bre","Breton"},
            {"bug","Buginese"},
            {"bul","Bulgarian"},
            {"bua","Buriat"},
            {"bur","Burmese"},
            {"cad","Caddo"},
            {"cat","Catalan; Valencian"},
            {"cau","Caucasian languages"},
            {"ceb","Cebuano"},
            {"cel","Celtic languages"},
            {"cai","Central American Indian languages"},
            {"khm","Central Khmer"},
            {"chg","Chagatai"},
            {"cmc","Chamic languages"},
            {"cha","Chamorro"},
            {"che","Chechen"},
            {"chr","Cherokee"},
            {"chy","Cheyenne"},
            {"chb","Chibcha"},
            {"nya","Chichewa; Chewa; Nyanja"},
            {"chi","Chinese"},
            {"chn","Chinook jargon"},
            {"chp","Chipewyan; Dene Suline"},
            {"cho","Choctaw"},
            {"chu","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
            {"chk","Chuukese"},
            {"chv","Chuvash"},
            {"nwc","Classical Newari; Old Newari; Classical Nepal Bhasa"},
            {"syc","Classical Syriac"},
            {"cop","Coptic"},
            {"cor","Cornish"},
            {"cos","Corsican"},
            {"cre","Cree"},
            {"mus","Creek"},
            {"crp","Creoles and pidgins"},
            {"cpe","Creoles and pidgins, English based"},
            {"cpf","Creoles and pidgins, French-based"},
            {"cpp","Creoles and pidgins, Portuguese-based"},
            {"crh","Crimean Tatar; Crimean Turkish"},
            {"hrv","Croatian"},
            {"cus","Cushitic languages"},
            {"cze","Czech"},
            {"dak","Dakota"},
            {"dan","Danish"},
            {"dar","Dargwa"},
            {"del","Delaware"},
            {"din","Dinka"},
            {"div","Divehi; Dhivehi; Maldivian"},
            {"doi","Dogri"},
            {"dgr","Dogrib"},
            {"dra","Dravidian languages"},
            {"dua","Duala"},
            {"dum","Dutch, Middle (ca.1050-1350)"},
            {"dut","Dutch; Flemish"},
            {"dyu","Dyula"},
            {"dzo","Dzongkha"},
            {"frs","Eastern Frisian"},
            {"efi","Efik"},
            {"egy","Egyptian (Ancient)"},
            {"eka","Ekajuk"},
            {"elx","Elamite"},
            {"eng","English"},
            {"enm","English, Middle (1100-1500)"},
            {"ang","English, Old (ca.450-1100)"},
            {"myv","Erzya"},
            {"epo","Esperanto"},
            {"est","Estonian"},
            {"ewe","Ewe"},
            {"ewo","Ewondo"},
            {"fan","Fang"},
            {"fat","Fanti"},
            {"fao","Faroese"},
            {"fij","Fijian"},
            {"fil","Filipino; Pilipino"},
            {"fin","Finnish"},
            {"fiu","Finno-Ugrian languages"},
            {"fon","Fon"},
            {"fre","French"},
            {"frm","French, Middle (ca.1400-1600)"},
            {"fro","French, Old (842-ca.1400)"},
            {"fur","Friulian"},
            {"ful","Fulah"},
            {"gaa","Ga"},
            {"gla","Gaelic; Scottish Gaelic"},
            {"car","Galibi Carib"},
            {"glg","Galician"},
            {"lug","Ganda"},
            {"gay","Gayo"},
            {"gba","Gbaya"},
            {"gez","Geez"},
            {"geo","Georgian"},
            {"ger","German"},
            {"gmh","German, Middle High (ca.1050-1500)"},
            {"goh","German, Old High (ca.750-1050)"},
            {"gem","Germanic languages"},
            {"gil","Gilbertese"},
            {"gon","Gondi"},
            {"gor","Gorontalo"},
            {"got","Gothic"},
            {"grb","Grebo"},
            {"grc","Greek, Ancient (to 1453)"},
            {"gre","Greek, Modern (1453-)"},
            {"grn","Guarani"},
            {"guj","Gujarati"},
            {"gwi","Gwich'in"},
            {"hai","Haida"},
            {"hat","Haitian; Haitian Creole"},
            {"hau","Hausa"},
            {"haw","Hawaiian"},
            {"heb","Hebrew"},
            {"her","Herero"},
            {"hil","Hiligaynon"},
            {"him","Himachali languages; Western Pahari languages"},
            {"hin","Hindi"},
            {"hmo","Hiri Motu"},
            {"hit","Hittite"},
            {"hmn","Hmong; Mong"},
            {"hun","Hungarian"},
            {"hup","Hupa"},
            {"iba","Iban"},
            {"ice","Icelandic"},
            {"ido","Ido"},
            {"ibo","Igbo"},
            {"ijo","Ijo languages"},
            {"ilo","Iloko"},
            {"smn","Inari Sami"},
            {"inc","Indic languages"},
            {"ine","Indo-European languages"},
            {"ind","Indonesian"},
            {"inh","Ingush"},
            {"ina","Interlingua (International Auxiliary Language Association)"},
            {"ile","Interlingue; Occidental"},
            {"iku","Inuktitut"},
            {"ipk","Inupiaq"},
            {"ira","Iranian languages"},
            {"gle","Irish"},
            {"mga","Irish, Middle (900-1200)"},
            {"sga","Irish, Old (to 900)"},
            {"iro","Iroquoian languages"},
            {"ita","Italian"},
            {"jpn","Japanese"},
            {"jav","Javanese"},
            {"jrb","Judeo-Arabic"},
            {"jpr","Judeo-Persian"},
            {"kbd","Kabardian"},
            {"kab","Kabyle"},
            {"kac","Kachin; Jingpho"},
            {"kal","Kalaallisut; Greenlandic"},
            {"xal","Kalmyk; Oirat"},
            {"kam","Kamba"},
            {"kan","Kannada"},
            {"kau","Kanuri"},
            {"kaa","Kara-Kalpak"},
            {"krc","Karachay-Balkar"},
            {"krl","Karelian"},
            {"kar","Karen languages"},
            {"kas","Kashmiri"},
            {"csb","Kashubian"},
            {"kaw","Kawi"},
            {"kaz","Kazakh"},
            {"kha","Khasi"},
            {"khi","Khoisan languages"},
            {"kho","Khotanese; Sakan"},
            {"kik","Kikuyu; Gikuyu"},
            {"kmb","Kimbundu"},
            {"kin","Kinyarwanda"},
            {"kir","Kirghiz; Kyrgyz"},
            {"tlh","Klingon; tlhIngan-Hol"},
            {"kom","Komi"},
            {"kon","Kongo"},
            {"kok","Konkani"},
            {"kor","Korean"},
            {"kos","Kosraean"},
            {"kpe","Kpelle"},
            {"kro","Kru languages"},
            {"kua","Kuanyama; Kwanyama"},
            {"kum","Kumyk"},
            {"kur","Kurdish"},
            {"kru","Kurukh"},
            {"kut","Kutenai"},
            {"lad","Ladino"},
            {"lah","Lahnda"},
            {"lam","Lamba"},
            {"day","Land Dayak languages"},
            {"lao","Lao"},
            {"lat","Latin"},
            {"lav","Latvian"},
            {"lez","Lezghian"},
            {"lim","Limburgan; Limburger; Limburgish"},
            {"lin","Lingala"},
            {"lit","Lithuanian"},
            {"jbo","Lojban"},
            {"nds","Low German; Low Saxon; German, Low; Saxon, Low"},
            {"dsb","Lower Sorbian"},
            {"loz","Lozi"},
            {"lub","Luba-Katanga"},
            {"lua","Luba-Lulua"},
            {"lui","Luiseno"},
            {"smj","Lule Sami"},
            {"lun","Lunda"},
            {"luo","Luo (Kenya and Tanzania)"},
            {"lus","Lushai"},
            {"ltz","Luxembourgish; Letzeburgesch"},
            {"mac","Macedonian"},
            {"mad","Madurese"},
            {"mag","Magahi"},
            {"mai","Maithili"},
            {"mak","Makasar"},
            {"mlg","Malagasy"},
            {"may","Malay"},
            {"mal","Malayalam"},
            {"mlt","Maltese"},
            {"mnc","Manchu"},
            {"mdr","Mandar"},
            {"man","Mandingo"},
            {"mni","Manipuri"},
            {"mno","Manobo languages"},
            {"glv","Manx"},
            {"mao","Maori"},
            {"arn","Mapudungun; Mapuche"},
            {"mar","Marathi"},
            {"chm","Mari"},
            {"mah","Marshallese"},
            {"mwr","Marwari"},
            {"mas","Masai"},
            {"myn","Mayan languages"},
            {"men","Mende"},
            {"mic","Mi'kmaq; Micmac"},
            {"min","Minangkabau"},
            {"mwl","Mirandese"},
            {"moh","Mohawk"},
            {"mdf","Moksha"},
            {"mkh","Mon-Khmer languages"},
            {"lol","Mongo"},
            {"mon","Mongolian"},
            {"mos","Mossi"},
            {"mul","Multiple languages"},
            {"mun","Munda languages"},
            {"nqo","N'Ko"},
            {"nah","Nahuatl languages"},
            {"nau","Nauru"},
            {"nav","Navajo; Navaho"},
            {"nde","Ndebele, North; North Ndebele"},
            {"nbl","Ndebele, South; South Ndebele"},
            {"ndo","Ndonga"},
            {"nap","Neapolitan"},
            {"new","Nepal Bhasa; Newari"},
            {"nep","Nepali"},
            {"nia","Nias"},
            {"nic","Niger-Kordofanian languages"},
            {"ssa","Nilo-Saharan languages"},
            {"niu","Niuean"},
            {"zxx","No linguistic content; Not applicable"},
            {"nog","Nogai"},
            {"non","Norse, Old"},
            {"nai","North American Indian languages"},
            {"frr","Northern Frisian"},
            {"sme","Northern Sami"},
            {"nno","Norwegian Nynorsk; Nynorsk, Norwegian"},
            {"nor","Norwegian"},
            {"nub","Nubian languages"},
            {"nym","Nyamwezi"},
            {"nyn","Nyankole"},
            {"nyo","Nyoro"},
            {"nzi","Nzima"},
            {"oci","Occitan (post 1500)"},
            {"arc","Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"},
            {"oji","Ojibwa"},
            {"ori","Oriya"},
            {"orm","Oromo"},
            {"osa","Osage"},
            {"oss","Ossetian; Ossetic"},
            {"oto","Otomian languages"},
            {"pal","Pahlavi"},
            {"pau","Palauan"},
            {"pli","Pali"},
            {"pam","Pampanga; Kapampangan"},
            {"pag","Pangasinan"},
            {"pan","Panjabi; Punjabi"},
            {"pap","Papiamento"},
            {"paa","Papuan languages"},
            {"nso","Pedi; Sepedi; Northern Sotho"},
            {"per","Persian"},
            {"peo","Persian, Old (ca.600-400 B.C.)"},
            {"phi","Philippine languages"},
            {"phn","Phoenician"},
            {"pon","Pohnpeian"},
            {"pol","Polish"},
            {"por","Portuguese"},
            {"pra","Prakrit languages"},
            {"pro","Provençal, Old (to 1500); Occitan, Old (to 1500)"},
            {"pus","Pushto; Pashto"},
            {"que","Quechua"},
            {"raj","Rajasthani"},
            {"rap","Rapanui"},
            {"rar","Rarotongan; Cook Islands Maori"},
            {"qaa","Reserved for local use: qaa"},
            {"qad","Reserved for local use: qad"},
            {"roa","Romance languages"},
            {"rum","Romanian; Moldavian; Moldovan"},
            {"roh","Romansh"},
            {"rom","Romany"},
            {"run","Rundi"},
            {"rus","Russian"},
            {"sal","Salishan languages"},
            {"sam","Samaritan Aramaic"},
            {"smi","Sami languages"},
            {"smo","Samoan"},
            {"sad","Sandawe"},
            {"sag","Sango"},
            {"san","Sanskrit"},
            {"sat","Santali"},
            {"srd","Sardinian"},
            {"sas","Sasak"},
            {"sco","Scots"},
            {"sel","Selkup"},
            {"sem","Semitic languages"},
            {"srp","Serbian"},
            {"srr","Serer"},
            {"shn","Shan"},
            {"sna","Shona"},
            {"iii","Sichuan Yi; Nuosu"},
            {"scn","Sicilian"},
            {"sid","Sidamo"},
            {"sgn","Sign Languages"},
            {"bla","Siksika"},
            {"snd","Sindhi"},
            {"sin","Sinhala; Sinhalese"},
            {"sit","Sino-Tibetan languages"},
            {"sio","Siouan languages"},
            {"sms","Skolt Sami"},
            {"den","Slave (Athapascan)"},
            {"sla","Slavic languages"},
            {"slo","Slovak"},
            {"slv","Slovenian"},
            {"sog","Sogdian"},
            {"som","Somali"},
            {"son","Songhai languages"},
            {"snk","Soninke"},
            {"wen","Sorbian languages"},
            {"sot","Sotho, Southern"},
            {"sai","South American Indian languages"},
            {"alt","Southern Altai"},
            {"sma","Southern Sami"},
            {"spa","Spanish; Castilian"},
            {"srn","Sranan Tongo"},
            {"zgh","Standard Moroccan Tamazight"},
            {"suk","Sukuma"},
            {"sux","Sumerian"},
            {"sun","Sundanese"},
            {"sus","Susu"},
            {"swa","Swahili"},
            {"ssw","Swati"},
            {"swe","Swedish"},
            {"gsw","Swiss German; Alemannic; Alsatian"},
            {"syr","Syriac"},
            {"tgl","Tagalog"},
            {"tah","Tahitian"},
            {"tai","Tai languages"},
            {"tgk","Tajik"},
            {"tmh","Tamashek"},
            {"tam","Tamil"},
            {"tat","Tatar"},
            {"tel","Telugu"},
            {"ter","Tereno"},
            {"tet","Tetum"},
            {"tha","Thai"},
            {"tib","Tibetan"},
            {"tig","Tigre"},
            {"tir","Tigrinya"},
            {"tem","Timne"},
            {"tiv","Tiv"},
            {"tli","Tlingit"},
            {"tpi","Tok Pisin"},
            {"tkl","Tokelau"},
            {"tog","Tonga (Nyasa)"},
            {"ton","Tonga (Tonga Islands)"},
            {"tsi","Tsimshian"},
            {"tso","Tsonga"},
            {"tsn","Tswana"},
            {"tum","Tumbuka"},
            {"tup","Tupi languages"},
            {"tur","Turkish"},
            {"ota","Turkish, Ottoman (1500-1928)"},
            {"tuk","Turkmen"},
            {"tvl","Tuvalu"},
            {"tyv","Tuvinian"},
            {"twi","Twi"},
            {"udm","Udmurt"},
            {"uga","Ugaritic"},
            {"uig","Uighur; Uyghur"},
            {"ukr","Ukrainian"},
            {"umb","Umbundu"},
            {"mis","Uncoded languages"},
            {"und","Undetermined"},
            {"hsb","Upper Sorbian"},
            {"urd","Urdu"},
            {"uzb","Uzbek"},
            {"vai","Vai"},
            {"ven","Venda"},
            {"vie","Vietnamese"},
            {"vol","Volapük"},
            {"vot","Votic"},
            {"wak","Wakashan languages"},
            {"wln","Walloon"},
            {"war","Waray"},
            {"was","Washo"},
            {"wel","Welsh"},
            {"fry","Western Frisian"},
            {"wal","Wolaitta; Wolaytta"},
            {"wol","Wolof"},
            {"xho","Xhosa"},
            {"sah","Yakut"},
            {"yao","Yao"},
            {"yap","Yapese"},
            {"yid","Yiddish"},
            {"yor","Yoruba"},
            {"ypk","Yupik languages"},
            {"znd","Zande languages"},
            {"zap","Zapotec"},
            {"zza","Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"},
            {"zen","Zenaga"},
            {"zha","Zhuang; Chuang"},
            {"zul","Zulu"},
            {"zun","Zuni"}
        };

        internal static string[] MachExtensions = new string[]
        {
            ".xml",
            ".txt"
        };

        internal static string[] mimeTypes = {
            "",
            "application/activemessage",
            "application/andrew-inset",
            "application/applefile",
            "application/atomicmail",
            "application/batch-SMTP",
            "application/beep+xml",
            "application/cals-1840",
            "application/commonground",
            "application/cu-seeme",
            "application/cybercash",
            "application/dca-rft",
            "application/dec-dx",
            "application/dsptype",
            "application/dvcs",
            "application/edi-consent",
            "application/EDI-Consent",
            "application/edifact",
            "application/EDIFACT",
            "application/edi-x12",
            "application/EDI-X12",
            "application/eshop",
            "application/font-tdpfr",
            "application/futuresplash",
            "application/ghostview",
            "application/hta",
            "application/http",
            "application/hyperstudio",
            "application/iges",
            "application/index",
            "application/index.cmd",
            "application/index.obj",
            "application/index.response",
            "application/index.vnd",
            "application/iotp",
            "application/ipp",
            "application/isup",
            "application/mac-binhex40",
            "application/mac-compactpro",
            "application/macwriteii",
            "application/marc",
            "application/mathematica",
            "application/mathematica-old",
            "application/msaccess",
            "application/msword",
            "application/news-message-id",
            "application/news-transmission",
            "application/ocsp-request",
            "application/ocsp-response",
            "application/octet-stream",
            "application/oda",
            "application/parityfec",
            "application/pdf",
            "application/pgp-encrypted",
            "application/pgp-keys",
            "application/pgp-signature",
            "application/pics-rules",
            "application/pkcs10",
            "application/pkcs7-mime",
            "application/pkcs7-signature",
            "application/pkix-cert",
            "application/pkixcmp",
            "application/pkix-crl",
            "application/postscript",
            "application/prs.alvestrand.titrax-sheet",
            "application/prs.cww",
            "application/prs.nprend",
            "application/qsig",
            "application/remote-printing",
            "application/riscos",
            "application/rtf",
            "application/sdp",
            "application/set-payment",
            "application/set-payment-initiation",
            "application/set-registration",
            "application/set-registration-initiation",
            "application/sgml",
            "application/sgml-open-catalog",
            "application/sieve",
            "application/slate",
            "application/smil",
            "application/timestamp-query",
            "application/timestamp-reply",
            "application/vemmi",
            "application/vnd.3M.Post-it-Notes",
            "application/vnd.accpac.simply.aso",
            "application/vnd.accpac.simply.imp",
            "application/vnd.acucobol",
            "application/vnd.aether.imp",
            "application/vnd.anser-web-certificate-issue-initiation",
            "application/vnd.anser-web-funds-transfer-initiation",
            "application/vnd.audiograph",
            "application/vnd.bmi",
            "application/vnd.businessobjects",
            "application/vnd.canon-cpdl",
            "application/vnd.canon-lips",
            "application/vnd.cinderella",
            "application/vnd.claymore",
            "application/vnd.$commerce_battelle",
            "application/vnd.commerce-battelle",
            "application/vnd.commonspace",
            "application/vnd.comsocaller",
            "application/vnd.contact.cmsg",
            "application/vnd.cosmocaller",
            "application/vnd.ctc-posml",
            "application/vnd.cups-postscript",
            "application/vnd.cups-raster",
            "application/vnd.cups-raw",
            "application/vnd.cybank",
            "application/vnd.dna",
            "application/vnd.dpgraph",
            "application/vnd.dxr",
            "application/vnd.ecdis-update",
            "application/vnd.ecowin.chart",
            "application/vnd.ecowin.filerequest",
            "application/vnd.ecowin.fileupdate",
            "application/vnd.ecowin.series",
            "application/vnd.ecowin.seriesrequest",
            "application/vnd.ecowin.seriesupdate",
            "application/vnd.enliven",
            "application/vnd.epson.esf",
            "application/vnd.epson.msf",
            "application/vnd.epson.quickanime",
            "application/vnd.epson.salt",
            "application/vnd.epson.ssf",
            "application/vnd.ericsson.quickcall",
            "application/vnd.eudora.data",
            "application/vnd.fdf",
            "application/vnd.ffsns",
            "application/vnd.flographit",
            "application/vnd.FloGraphIt",
            "application/vnd.framemaker",
            "application/vnd.fsc.weblaunch",
            "application/vnd.fujitsu.oasys",
            "application/vnd.fujitsu.oasys2",
            "application/vnd.fujitsu.oasys3",
            "application/vnd.fujitsu.oasysgp",
            "application/vnd.fujitsu.oasysprs",
            "application/vnd.fujixerox.ddd",
            "application/vnd.fujixerox.docuworks",
            "application/vnd.fujixerox.docuworks.binder",
            "application/vnd.fut-misnet",
            "application/vnd.grafeq",
            "application/vnd.groove-account",
            "application/vnd.groove-identity-message",
            "application/vnd.groove-injector",
            "application/vnd.groove-tool-message",
            "application/vnd.groove-tool-template",
            "application/vnd.groove-vcard",
            "application/vnd.hhe.lesson-player",
            "application/vnd.hp-HPGL",
            "application/vnd.hp-hpid",
            "application/vnd.hp-hps",
            "application/vnd.hp-PCL",
            "application/vnd.hp-PCLXL",
            "application/vnd.httphone",
            "application/vnd.hzn-3d-crossword",
            "application/vnd.ibm.afplinedata",
            "application/vnd.ibm.MiniPay",
            "application/vnd.ibm.modcap",
            "application/vnd.informix-visionary",
            "application/vnd.intercon.formnet",
            "application/vnd.intertrust.digibox",
            "application/vnd.intertrust.nncp",
            "application/vnd.intu.qbo",
            "application/vnd.intu.qfx",
            "application/vnd.irepository.package+xml",
            "application/vnd.is-xpr",
            "application/vnd.japannet-directory-service",
            "application/vnd.japannet-jpnstore-wakeup",
            "application/vnd.japannet-payment-wakeup",
            "application/vnd.japannet-registration",
            "application/vnd.japannet-registration-wakeup",
            "application/vnd.japannet-setstore-wakeup",
            "application/vnd.japannet-verification",
            "application/vnd.japannet-verification-wakeup",
            "application/vnd.koan",
            "application/vnd.lotus-1-2-3",
            "application/vnd.lotus-approach",
            "application/vnd.lotus-freelance",
            "application/vnd.lotus-notes",
            "application/vnd.lotus-organizer",
            "application/vnd.lotus-screencam",
            "application/vnd.lotus-wordpro",
            "application/vnd.mcd",
            "application/vnd.mediastation.cdkey",
            "application/vnd.meridian-slingshot",
            "application/vnd.mif",
            "application/vnd.minisoft-hp3000-save",
            "application/vnd.mitsubishi.misty-guard.trustweb",
            "application/vnd.mobius.daf",
            "application/vnd.Mobius.DAF",
            "application/vnd.mobius.dis",
            "application/vnd.Mobius.DIS",
            "application/vnd.Mobius.MBK",
            "application/vnd.Mobius.MQY",
            "application/vnd.mobius.msl",
            "application/vnd.Mobius.MSL",
            "application/vnd.mobius.plc",
            "application/vnd.Mobius.PLC",
            "application/vnd.mobius.txf",
            "application/vnd.Mobius.TXF",
            "application/vnd.motorola.flexsuite",
            "application/vnd.motorola.flexsuite.adsi",
            "application/vnd.motorola.flexsuite.fis",
            "application/vnd.motorola.flexsuite.gotap",
            "application/vnd.motorola.flexsuite.kmr",
            "application/vnd.motorola.flexsuite.ttc",
            "application/vnd.motorola.flexsuite.wem",
            "application/vnd.mozilla.xul+xml",
            "application/vnd.ms-artgalry",
            "application/vnd.ms-asf",
            "application/vnd.mseq",
            "application/vnd.ms-excel",
            "application/vnd.msign",
            "application/vnd.ms-lrm",
            "application/vnd.ms-pki.seccat",
            "application/vnd.ms-pki.stl",
            "application/vnd.ms-powerpoint",
            "application/vnd.ms-project",
            "application/vnd.ms-tnef",
            "application/vnd.ms-works",
            "application/vnd.musician",
            "application/vnd.music-niff",
            "application/vnd.netfpx",
            "application/vnd.noblenet-directory",
            "application/vnd.noblenet-sealer",
            "application/vnd.noblenet-web",
            "application/vnd.novadigm.EDM",
            "application/vnd.novadigm.EDX",
            "application/vnd.novadigm.EXT",
            "application/vnd.osa.netdeploy",
            "application/vnd.palm",
            "application/vnd.pg.format",
            "application/vnd.pg.osasli",
            "application/vnd.powerbuilder6",
            "application/vnd.powerbuilder6-s",
            "application/vnd.powerbuilder7",
            "application/vnd.powerbuilder75",
            "application/vnd.powerbuilder75-s",
            "application/vnd.powerbuilder7-s",
            "application/vnd.previewsystems.box",
            "application/vnd.publishare-delta-tree",
            "application/vnd.pvi.ptid1",
            "application/vnd.pwg-xhtml-print+xml",
            "application/vnd.rapid",
            "application/vnd.s3sms",
            "application/vnd.seemail",
            "application/vnd.shana.informed.formdata",
            "application/vnd.shana.informed.formtemplate",
            "application/vnd.shana.informed.interchange",
            "application/vnd.shana.informed.package",
            "application/vnd.sss-cod",
            "application/vnd.sss-dtf",
            "application/vnd.sss-ntf",
            "application/vnd.stardivision.calc",
            "application/vnd.stardivision.draw",
            "application/vnd.stardivision.impress",
            "application/vnd.stardivision.math",
            "application/vnd.stardivision.writer",
            "application/vnd.stardivision.writer-global",
            "application/vnd.street-stream",
            "application/vnd.sun.xml.calc",
            "application/vnd.sun.xml.calc.template",
            "application/vnd.sun.xml.draw",
            "application/vnd.sun.xml.draw.template",
            "application/vnd.sun.xml.impress",
            "application/vnd.sun.xml.impress.template",
            "application/vnd.sun.xml.math",
            "application/vnd.sun.xml.writer",
            "application/vnd.sun.xml.writer.global",
            "application/vnd.sun.xml.writer.template",
            "application/vnd.svd",
            "application/vnd.swiftview-ics",
            "application/vnd.triscape.mxs",
            "application/vnd.trueapp",
            "application/vnd.truedoc",
            "application/vnd.tve-trigger",
            "application/vnd.ufdl",
            "application/vnd.uplanet.alert",
            "application/vnd.uplanet.alert-wbxml",
            "application/vnd.uplanet.bearer-choice",
            "application/vnd.uplanet.bearer-choice-wbxml",
            "application/vnd.uplanet.cacheop",
            "application/vnd.uplanet.cacheop-wbxml",
            "application/vnd.uplanet.channel",
            "application/vnd.uplanet.channel-wbxml",
            "application/vnd.uplanet.list",
            "application/vnd.uplanet.listcmd",
            "application/vnd.uplanet.listcmd-wbxml",
            "application/vnd.uplanet.list-wbxml",
            "application/vnd.uplanet.signal",
            "application/vnd.vcx",
            "application/vnd.vectorworks",
            "application/vnd.vidsoft.vidconference",
            "application/vnd.visio",
            "application/vnd.vividence.scriptfile",
            "application/vnd.wap.sic",
            "application/vnd.wap.slc",
            "application/vnd.wap.wbxml",
            "application/vnd.wap.wmlc",
            "application/vnd.wap.wmlscriptc",
            "application/vnd.webturbo",
            "application/vnd.wrq-hp3000-labelled",
            "application/vnd.wt.stf",
            "application/vnd.xara",
            "application/vnd.xfdl",
            "application/vnd.yellowriver-custom-menu",
            "application/whoispp-query",
            "application/whoispp-response",
            "application/wita",
            "application/wordperfect5.1",
            "application/x-123",
            "application/x400-bp",
            "application/x-bcpio",
            "application/x-cdf",
            "application/x-cdlink",
            "application/x-chess-pgn",
            "application/x-core",
            "application/x-cpio",
            "application/x-csh",
            "application/x-debian-package",
            "application/x-director",
            "application/x-dms",
            "application/x-doom",
            "application/x-dvi",
            "application/x-executable",
            "application/x-font",
            "application/x-futuresplash",
            "application/x-gnumeric",
            "application/x-graphing-calculator",
            "application/x-gtar",
            "application/x-hdf",
            "application/xhtml+xml",
            "application/x-httpd-php",
            "application/x-httpd-php3",
            "application/x-httpd-php3-preprocessed",
            "application/x-httpd-php4",
            "application/x-httpd-php-source",
            "application/x-ica",
            "application/x-internet-signup",
            "application/x-iphone",
            "application/x-java-applet",
            "application/x-java-archive",
            "application/x-java-bean",
            "application/x-java-jnlp-file",
            "application/x-javascript",
            "application/x-java-serialized-object",
            "application/x-java-vm",
            "application/x-kchart",
            "application/x-kdelnk",
            "application/x-killustrator",
            "application/x-koan",
            "application/x-kpresenter",
            "application/x-kspread",
            "application/x-kword",
            "application/x-latex",
            "application/x-lha",
            "application/x-lzh",
            "application/x-lzx",
            "application/x-maker",
            "application/x-mif",
            "application/xml",
            "application/xml-dtd",
            "application/xml-external-parsed-entity",
            "application/x-msdos-program",
            "application/x-msi",
            "application/x-ms-wmd",
            "application/x-ms-wmz",
            "application/x-netcdf",
            "application/x-ns-proxy-autoconfig",
            "application/x-object",
            "application/x-ogg",
            "application/x-oz-application",
            "application/x-perl",
            "application/x-pkcs7-certreqresp",
            "application/x-pkcs7-crl",
            "application/x-quicktimeplayer",
            "application/x-redhat-package-manager",
            "application/x-rx",
            "application/x-sh",
            "application/x-shar",
            "application/x-shellscript",
            "application/x-shockwave-flash",
            "application/x-stuffit",
            "application/x-sv4cpio",
            "application/x-sv4crc",
            "application/x-tar",
            "application/x-tcl",
            "application/x-tex",
            "application/x-tex-gf",
            "application/x-texinfo",
            "application/x-tex-pk",
            "application/x-trash",
            "application/x-troff",
            "application/x-troff-man",
            "application/x-troff-me",
            "application/x-troff-ms",
            "application/x-truetype-font",
            "application/x-ustar",
            "application/x-wais-source",
            "application/x-wingz",
            "application/x-x509-ca-cert",
            "application/x-xfig",
            "application/zip",
            "audio/32kadpcm",
            "audio/basic",
            "audio/DAT12",
            "audio/g.722.1",
            "audio/G.722.1",
            "audio/l16",
            "audio/L16",
            "audio/L20",
            "audio/L24",
            "audio/midi",
            "audio/mp4a-latm",
            "audio/MP4A-LATM",
            "audio/mpa-robust",
            "audio/mpeg",
            "audio/mpegurl",
            "audio/parityfec",
            "audio/prs.sid",
            "audio/telephone-event",
            "audio/tone",
            "audio/vnd.cisco.nse",
            "audio/vnd.cns.anp1",
            "audio/vnd.cns.inf1",
            "audio/vnd.digital-winds",
            "audio/vnd.everad.plj",
            "audio/vnd.lucent.voice",
            "audio/vnd.nortel.vbk",
            "audio/vnd.nuera.ecelp4800",
            "audio/vnd.nuera.ecelp7470",
            "audio/vnd.nuera.ecelp9600",
            "audio/vnd.octel.sbc",
            "audio/vnd.qcelp",
            "audio/vnd.rhetorex.32kadpcm",
            "audio/vnd.vmx.cvsd",
            "audio/x-aiff",
            "audio/x-gsm",
            "audio/x-mpegurl",
            "audio/x-ms-wax",
            "audio/x-ms-wma",
            "audio/x-pn-realaudio",
            "audio/x-pn-realaudio-plugin",
            "audio/x-realaudio",
            "audio/x-scpls",
            "audio/x-sd2",
            "audio/x-wav",
            "chemical/x-pdb",
            "chemical/x-xyz",
            "font/sfnt",
            "font/ttf",
            "font/otf" ,
            "font/collection",
            "font/woff",
            "font/woff2",
            "image/bmp",
            "image/cgm",
            "image/cgmComputerGraphicsMetafile",
            "image/g3fax",
            "image/gif",
            "image/ief",
            "image/iefImageExchangeFormat",
            "image/jpeg",
            "image/naplps",
            "image/pcx",
            "image/png",
            "image/prs.btif",
            "image/prs.pti",
            "image/svg+xml",
            "image/svg+xml-compressed",
            "image/tiff",
            "image/tiffTagImageFileFormat",
            "image/vnd.cns.inf2",
            "image/vnd.dwg",
            "image/vnd.dxf",
            "image/vnd.fastbidsheet",
            "image/vnd.fpx",
            "image/vnd.fst",
            "image/vnd.fujixerox.edmics-mmr",
            "image/vnd.fujixerox.edmics-rlc",
            "image/vnd.mix",
            "image/vnd.net-fpx",
            "image/vnd.svf",
            "image/vnd.wap.wbmp",
            "image/vnd.xiff",
            "image/x-cmu-raster",
            "image/x-coreldraw",
            "image/x-coreldrawpattern",
            "image/x-coreldrawtemplate",
            "image/x-corelphotopaint",
            "image/x-djvu",
            "image/x-jg",
            "image/x-jng",
            "image/x-ms-bmp",
            "image/x-photoshop",
            "image/x-portable-anymap",
            "image/x-portable-bitmap",
            "image/x-portable-graymap",
            "image/x-portable-pixmap",
            "image/x-rgb",
            "image/x-xbitmap",
            "image/x-xpixmap",
            "image/x-xwindowdump",
            "image/webp",
            "inode/blockdevice",
            "inode/chardevice",
            "inode/directory",
            "inode/directory-locked",
            "inode/fifo",
            "inode/socket",
            "message/delivery-status",
            "message/disposition-notification",
            "message/external-body",
            "message/http",
            "message/news",
            "message/partial",
            "message/rfc822",
            "message/s-http",
            "model/iges",
            "model/mesh",
            "model/vnd.dwf",
            "model/vnd.flatland.3dml",
            "model/vnd.gdl",
            "model/vnd.gs-gdl",
            "model/vnd.gtw",
            "model/vnd.mts",
            "model/vnd.parasolid.transmit.binary",
            "model/vnd.parasolid.transmit.text",
            "model/vnd.vtu",
            "model/vrml",
            "multipart/alternative",
            "multipart/appledouble",
            "multipart/byteranges",
            "multipart/digest",
            "multipart/encrypted",
            "multipart/form-data",
            "multipart/header-set",
            "multipart/mixed",
            "multipart/parallel",
            "multipart/related",
            "multipart/report",
            "multipart/signed",
            "multipart/voice-message",
            "text/calendar",
            "text/comma-separated-values",
            "text/css",
            "text/directory",
            "text/english",
            "text/enriched",
            "text/h323",
            "text/html",
            "text/iuls",
            "text/mathml",
            "text/parityfec",
            "text/plain",
            "text/prs.lines.tag",
            "text/rfc822-headers",
            "text/richtext",
            "text/rtf",
            "text/scriptlet",
            "text/sgml",
            "text/t140",
            "text/tab-separated-values",
            "text/texmacs",
            "text/uri-list",
            "text/vnd.abc",
            "text/vnd.curl",
            "text/vnd.DMClientScript",
            "text/vnd.flatland.3dml",
            "text/vnd.fly",
            "text/vnd.fmi.flexstor",
            "text/vnd.in3d.3dml",
            "text/vnd.in3d.spot",
            "text/vnd.IPTC.NewsML",
            "text/vnd.IPTC.NITF",
            "text/vnd.latex-z",
            "text/vnd.motorola.reflex",
            "text/vnd.ms-mediapackage",
            "text/vnd.wap.si",
            "text/vnd.wap.sl",
            "text/vnd.wap.wml",
            "text/vnd.wap.wmlscript",
            "text/x-chdr",
            "text/x-c++hdr",
            "text/x-crontab",
            "text/x-csh",
            "text/x-csrc",
            "text/x-c++src",
            "text/x-java",
            "text/x-makefile",
            "text/xml",
            "text/xml-external-parsed-entity",
            "text/x-moc",
            "text/x-pascal",
            "text/x-server-parsed-html",
            "text/x-setext",
            "text/x-sh",
            "text/x-tcl",
            "text/x-tex",
            "text/x-vcalendar",
            "text/x-vcard",
            "video/dl",
            "video/fli",
            "video/gl",
            "video/mp4v-es",
            "video/MP4V-ES",
            "video/mpeg",
            "video/parityfec",
            "video/pointer",
            "video/quicktime",
            "video/vnd.fvt",
            "video/vnd.motorola.video",
            "video/vnd.motorola.videop",
            "video/vnd.mpegurl",
            "video/vnd.mts",
            "video/vnd.nokia.interleaved-multimedia",
            "video/vnd.vivo",
            "video/x-dv",
            "video/x-la-asf",
            "video/x-mng",
            "video/x-ms-asf",
            "video/x-msvideo",
            "video/x-ms-wm",
            "video/x-ms-wmv",
            "video/x-ms-wmx",
            "video/x-ms-wvx",
            "video/x-sgi-movie",
            "x-conference/x-cooltalk",
            "x-world/x-vrml"
        };

    }
}
